version: '3.1'
 
services:
  runner:
    build: .
    volumes:
      - .:/app
    command:
      - python
      - main.py
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      runner.env
