version: '3.1'
 
services:
  runner:
    build: .
    volumes:
      - .:/app
    command:
      - python
      - main.py
    network_mode: host
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      runner.env
